AWSTemplateFormatVersion: "2010-09-09"
Description: "Raspberry Pi Status Monitor"
Parameters:
  PiLocation:
    Type: String
    Description: Where is the Pi location?
  Threshold:
    Type: Number
    Description: Alarm Threshhold
  Period:
    Type: Number
    Description: How often data is placed in seconds
Resources:
  SpeedMetric:
    Type: AWS::CloudWatch::Alarm
    Properties:
      MetricName: !Sub ${PiLocation}NetworkSpeed
      AlarmName: !Sub ${PiLocation}NetworkSpeed
      # AlarmActions: 
      #   - TODO
      ComparisonOperator: LessThanOrEqualToThreshold
      DatapointsToAlarm: 1
      EvaluationPeriods: 2
      # InsufficientDataActions: 
      #   - TODO
      Namespace: !Sub NetworkSpeed/${PiLocation}
      # OKActions: 
      #   - TODO
      Period: !Ref Period
      Statistic: Average
      Threshold: !Ref Threshold
      TreatMissingData: breaching
      Unit: "Megabits/Second"
      Tags: 
        - Key: Project
          Value: pi-status-monitor
